# Generated by Django 4.2.1 on 2023-07-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
